name: Bug Report
description: Create a bug report
labels: ["defect"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
      placeholder: |
        Please use the CakePHP Slack channel, Discord channel or IRC channel for questions.

        https://cakephp.org/get-involved#getHelp
    validations:
      required: true
  - type: input
    attributes:
      label: Bake Version
      description: "The version of Bake."
      placeholder: "4.3.0"
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: "The version of CakePHP used."
      placeholder: "4.4"
    validations:
      required: false
